#!/bin/bash

if [ $(whoami) != "root" ];
  then
  printf "Warning: `basename $0` must be run by root.  Exiting...\n";
  exit 1
fi

apt-get install puppet-common tasksel;
tasksel install lamp-server;

echo "You will now configure your web root. Find <Directory /var/www/> section and set AllowOverride All."
read -p "Press Enter to continue..."
nano /etc/apache2/sites-available/default;

apt-get install drush phpmyadmin php5-xdebug;
/usr/sbin/a2enmod rewrite;
/usr/sbin/a2enmod userdir;

echo "You will now configure your PHP.ini."
echo "Make sure there is exactly one occurrence of:"
echo "[xdebug]"
echo "xdebug.remote_enable = On"
read -p "Press Enter to continue..."
nano /etc/php5/apache2/php.ini;


/etc/init.d/apache2 restart;

# install puppet scripts
PP_PATH=/usr/share/puppet/modules/drupie/manifests;
mkdir -p $PP_PATH;
cp site.pp $PP_PATH;
cp contribmodule.pp $PP_PATH;
