#!/bin/bash

if [ $(whoami) != "root" ];
  then
  printf "Warning: `basename $0` must be run by root.  Exiting...\n";
  exit 1
fi

apt-get install puppet-common tasksel;
tasksel install lamp-server;

echo "You will now configure your web root. Find <Directory /var/www/> section and set AllowOverride All."
read -p "Press Enter to continue..."
nano /etc/apache2/sites-available/default;

apt-get install drush phpmyadmin;
/usr/sbin/a2enmod rewrite;
/usr/sbin/a2enmod userdir;
/etc/init.d/apache2 restart;

#TODO: Copy puppet scripts where they belong so it can be used.